### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by CaptaiNiveau** [gileli121/GlassCode#22]
Hi, this plugin is great.

I'd love to be able to use it, which means I need to change a few things like update it and make it compatible with Linux.
Since there's no license, however, I had to delete my fork.

Could you please update this repo with a license to make this actually open source?
That'd be awesome!

If you've done this, I'll try my best to make this run on Linux as well.
Others have reported that it might sometimes work, I suspect this is depending on the GPU inside of the system.

Thanks!

**Comment by gileli121** [comment]
@CaptaiNiveau 
It's great to hear that someone wants to continue my hard efforts.
I added a license
https://github.com/gileli121/GlassCode/blob/main/LICENSE

To port it to Linux, I suggest first making sure that these API capabilities are available (probably should be since it is Linux.. But you should start with it first anyway):

## Needed OS APIs
* Fast capturing of a specific window while making it *only* fully transparent (but still allowing it to be interactable)
* Access the captured frame (pixels) - read & write to the frame while doing fast
* Draw above the window the captured frame in real-time (you draw the frame above the transparent window that is not visible because of transparency)

Keep in mind that all of these basic capabilities should run fast because this is before you do additional image processing.
If you verified that all of these are possible in Linux, you probably did halfway if you want to use the same code that does the image processing. That code does not have to change; it only cares about the frame data, and once you figure out how to get it, you can reuse it.

The other code (The display-layer and capture-layer files)  will need a version for Linux since it is 100% dependent on OS API calls.

Good luck!

**Comment by gileli121** [comment]
I assumed that Linux does not have a more native way of rendering Windows because I thought about Linux as a closed system like Windows (by mistake).
In Windows 10 & 11, it may be some kind of workaround (make the window transparent + draw frame above it, etc..)
But maybe in Linux, there is a more native way that the system exposes a hook for this task (since Linux is open-source). Maybe there is a shorter way.

So, if there is some native way in Linux to hook into the process of drawing windows, it is worth checking it instead of doing it like I did.

**Comment by CaptaiNiveau** [comment]
I can confirm that it's definitely possible, as many apps like the terminal emulator Kitty support this. 
I'm running Hyprland, which itself supports transparency for every app - however if you turn that on it'll make everything transparent, even the parts that shouldn't be. 

As you said, I also assume there's some kind of API or hook to get this information to render the own frame.
Since you've added the license I'll look into this now :D
Hyprland also has global settings for the blur applied to transparent windows, which implies that there's some kind of transparency buffer (?) provided by Hyprland.

My scope is Hyprland and therefore Wayland, but since Rider (or IntelliJ) currently doesn't support Wayland natively I'll assume that there's some specific stuff I'll have to watch out for. I think especially Hyprland users would appreciate this kind of eye candy, as that's what Hyprland's all about ^^

JetBrains are currently working on porting the Java GUI toolkit that they're using to Wayland. They said they'll put out a beta soon, so I'm hoping for the next few months on that.

**Comment by gileli121** [comment]
Nice :)
I don't know what "Wayland" is, but I believe you know what you are doing. I am very experienced with Windows API, but for Linux, I don't have knowledge like that.

You will also need to figure out how to blur and reduce the light through the window (if you want to implement it).
In my workaround, I created an additional black window between the target window and the window with the frame.

The black window is without any borders and is unclickable (just like the window with the processed frame/pixels), and it has some level of opacity. Opacity + black acts as a filter to reduce lightness. 
For the blurring effect, I used an OS API call to apply the blurring effect natively.

Good luck

**Comment by CaptaiNiveau** [comment]
Admittedly I don't know much about these lower level APIs, just the general desktop stuff in Linux.
However, I do want to get more into that and this seems like a good way.

I'll try to look at how other apps like Kitty have done it and see if a similar approach is doable (both at all and for myself, lol).
