### ISSUE TITLE
GlassCode is not compatible with 2021.1 releases

### ISSUE THREAD

**Issue by GoBigorGoHome** [gileli121/GlassCode#5]
Tested on CLion 2021.1.

**Comment by EncryptedCurse** [comment]
In the meantime, I was able to get around this using these steps:

1.  Download the latest plugin ZIP from [JetBrains Marketplace](https://plugins.jetbrains.com/plugin/15868-glasscode-for-windows-/versions)
2. Open the archive and navigate to `glasscode/lib/glasscode-1.2.1-SNAPSHOT.jar/META-INF`
3. Edit `until-build` in `plugin.xml` to say `"211.*"` instead of `"203.*"`
4. Install plugin ZIP from disk

I just started using GlassCode so I'm not sure if this breaks anything, but it appears to work.

**Comment by gileli121** [comment]
Thanks
I am not sure that I should ask you to do PR about this issue because maybe the source code under JAVA is not updated to last version.

Currently I am very busy in working on these stuff about WindowTop project
https://github.com/gileli121/WindowTop/issues?q=is%3Aissue+is%3Aopen+label%3Aplaned-for-v5.%28X%2B1%29.Y

Because the WindowTop project much more successful.
But looks like this project also start to get more attention from people so I hope soon to find the time.

The first thing I will do is to make sure that everything under JAVA (The source code of the plugin. Not the source code of Renderer.exe) will be updated here so we can get PRs 

It will help more to keep developing this project :)

**Comment by gileli121** [comment]
I am working on fix now

**Comment by gileli121** [comment]
@EncryptedCurse 

The source code is already updated.
I don't have time to fix it now.
You can do PR :) 

Thanks

**Comment by gileli121** [comment]
All source codes are now released including under CPP (The code of Renderer.exe)
https://github.com/gileli121/GlassCode/tree/main/CPP

**Comment by gileli121** [comment]
@GoBigorGoHome  @EncryptedCurse 
Fixed. Download from here:
https://github.com/gileli121/GlassCode/releases/tag/1.2.2

It will soon be available from jetbrains store as well

**Comment by gileli121** [comment]
The issue fixed and new version released that will work on 2021.1 releases
